name: Translations Diff

on:
  pull_request_review:
  pull_request:
    types: [opened, edited, synchronize, ready_for_review]
    branches:
      - development
      - main

jobs:
  translation:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout Base Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          path: hyve-lite-base
      - name: Setup node 22
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
      - name: Checkout PR Branch (Head)
        uses: actions/checkout@v4
        with:
          path: hyve-lite-head
      - name: Build POT for PR Branch
        run: |
          chmod +x ./hyve-lite-head/bin/make-pot.sh
          ./hyve-lite-head/bin/make-pot.sh ./hyve-lite-head ./hyve-lite-head/languages/hyve-lite.pot
          ls ./hyve-lite-head/languages/
      - name: Build POT for Base Branch
        run: |
          ./hyve-lite-head/bin/make-pot.sh ./hyve-lite-base ./hyve-lite-base/languages/hyve-lite.pot
          ls ./hyve-lite-base/languages/
      - name: Compare POT files
        uses: Codeinwp/action-i18n-string-reviewer@main
        with:
          fail-on-changes: "false"
          openrouter-key: ${{ secrets.OPEN_ROUTER_API_KEY }}
          openrouter-model: "google/gemini-2.5-flash"
          base-pot-file: "hyve-lite-base/languages/hyve-lite.pot"
          target-pot-file: "hyve-lite-head/languages/hyve-lite.pot"
          github-token: ${{ secrets.BOT_TOKEN }}
